services:
  mysql:
    image: mysql:8
    container_name: rollcall-db
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: ciecapstone2023db
    ports:
      - "3306:3306"
    networks:
      - rollcall-network
    volumes:
      - rollcall:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

  app:
    build:
      context: .
    container_name: rollcall
    ports:
      - "8443:8443"
    networks:
      - rollcall-network
    depends_on:
      - mysql
    environment:
      SERVER_PORT: 8443
      MQTT_PORT: 8883
      MQTT_SERVER: 181314a4c00344d5a62cfc8c2059208e.s1.eu.hivemq.cloud
      MQTT_USERNAME: "user1"
      MQTT_PASSWORD: "P@ssw0rd"
      DOWNLOAD_URL: http://localhost:8080
      MYSQL_HOST: rollcall-db
      MYSQL_DBNAME: ciecapstone2023db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123

volumes:
  rollcall:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/rollcall

networks:
  rollcall-network:
    driver: bridge